#!/usr/bin/env python                                                                                                                  

fileLists = { 'TWDilepton':['TWChannelDilepton',['../output/ntuple_SysTrees_TWChannelDilepton.root','../output/ntuple_SysTrees_TbarWChannelDilepton.root'],'TWDilepton.root'],
              'TTbarDilepton':['TTBarDilepton',['../output/ntuple_SysTrees_TTBarDilepton.root'],'TTbarDilepton.root'],
              'TWChannel':['TWChannel',['../output/ntuple_SysTrees_TWChannel.root'],'TWChannel.root'],
              'TTbar':['TTBar',['../output/ntuple_SysTrees_TTBar.root'],'TTbar.root'],
              'TChannel':['TChannel',['../output/ntuple_SysTrees_TChannel.root','../output/ntuple_SysTrees_TbarChannel.root'],'TChannel.root'],
              'SChannel':['SChannel',['../output/ntuple_SysTrees_SChannel.root','../output/ntuple_SysTrees_SbarChannel.root'],'SChannel.root'],
              'ZJets':['ZJets',['../output/ntuple_SysTrees_ZJets.root','../output/ntuple_SysTrees_ZJetsLowMass'],'ZJets.root'],
              'WJets':['WJets',['../output/ntuple_SysTrees_WJets.root'],'WJets.root'],
              'WW':['WW',['../output/ntuple_SysTrees_WW.root'],'WW.root'],
              'ZZ':['ZZ',['../output/ntuple_SysTrees_ZZ.root'],'ZZ.root'],
              'WZ':['WZ',['../output/ntuple_SysTrees_WZ.root'],'WZ.root'],
              'TWChannel_DS':['TWChannel',['../output/ntuple_SysTrees_TWChannel_DS.root','../output/ntuple_SysTrees_TbarWChannel_DS.root'],'TWChannel_DS.root'],
              'TWChannel_Q2Up':['TWChannel_Q2Up',['../output/ntuple_SysTrees_TWChannel_Q2Up.root','../output/ntuple_SysTrees_TbarWChannel_Q2Up.root'],'TWChannel_Q2Up.root'],
              'TWChannel_Q2Down':['TWChannel_Q2Down',['../output/ntuple_SysTrees_TWChannel_Q2Down.root','../output/ntuple_SysTrees_TbarWChannel_Q2Down.root'],'TWChannel_Q2Down.root'],
              'TTBar_Q2Up':['TTBar_Q2Up',['../output/ntuple_SysTrees_TTBar_Q2Up.root'],'TTBar_Q2Up.root'],
              'TTBar_Q2Down':['TTBar_Q2Down',['../output/ntuple_SysTrees_TTBar_Q2Down.root'],'TTBar_Q2Down.root'],
              'TTBar_MatchingUp':['TTBar_MatchingUp',['../output/ntuple_SysTrees_TTBar_MatchingUp.root'],'TTBar_MatchingUp.root'],
              'TTBar_MatchingDown':['TTBar_MatchingDown',['../output/ntuple_SysTrees_TTBar_MatchingDown.root'],'TTBar_MatchingDown.root'],
              'TTBar_Mass166_5':['TTBar_Mass166_5',['../output/ntuple_SysTrees_TTBar_Mass166_5.root'],'TTBar_Mass166_5.root'],
              'TTBar_Mass178_5':['TTBar_Mass178_5',['../output/ntuple_SysTrees_TTBar_Mass178_5.root'],'TTBar_Mass178_5.root'],
              'TWChannel_Mass166_5':['TWChannel_Mass166_5',['../output/ntuple_SysTrees_TWChannel_Mass166_5.root','../output/ntuple_SysTrees_TbarWChannel_Mass166_5.root'],'TWChannel_Mass166_5.root'],
              'TWChannel_Mass178_5':['TWChannel_Mass178_5',['../output/ntuple_SysTrees_TWChannel_Mass178_5.root','../output/ntuple_SysTrees_TbarWChannel_Mass178_5.root'],'TWChannel_Mass178_5.root'],
              }
